FROM nginx:alpine
MAINTAINER Hungnv
# change nginx conf file
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
RUN mkdir -p /var/www/html/public

WORKDIR /var/www/html/public

# add source to working directory
ADD ./public /var/www/html/public

RUN ls -la

CMD ["nginx","-g","daemon off;"]
