version: "3.5"
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/code
    ports:
      - 80:80
    networks:
      - nginx
    depends_on:
      - php
      - mysql
  php:
    container_name: hello12/php:latest
    networks:
      - nginx
  mysql:
    container_name: my_sql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
    - 3306:3306
    networks:
      - nginx


networks:
  nginx:
    driver: bridge
